<a href="https://colab.research.google.com/github/Nitesh-Projects/ML-Projects/blob/master/Mercedez_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
import matplotlib.pyplot as plt


In [6]:
from google.colab import files
uploaded = files.upload()

Saving mercedesBenzData.csv to mercedesBenzData.csv


In [8]:
import io
data = pd.read_csv(io.BytesIO(uploaded['mercedesBenzData.csv']))

In [9]:
data.head()

ID       y  X0 X1  X2 X3 X4  ... X378 X379 X380  X382  X383  X384  X385
0   0  130.81   k  v  at  a  d  ...    0    0    0     0     0     0     0
1   6   88.53   k  t  av  e  d  ...    0    0    0     0     0     0     0
2   7   76.26  az  w   n  c  d  ...    0    0    0     1     0     0     0
3   9   80.62  az  t   n  f  d  ...    0    0    0     0     0     0     0
4  13   78.02  az  v   n  f  d  ...    0    0    0     0     0     0     0

[5 rows x 378 columns]

In [10]:
data.shape

(4209, 378)

In [11]:
cat_data = data.iloc[:,2:10]

In [13]:
cat_data.head()

X0 X1  X2 X3 X4 X5 X6 X8
0   k  v  at  a  d  u  j  o
1   k  t  av  e  d  y  l  o
2  az  w   n  c  d  x  j  x
3  az  t   n  f  d  x  l  e
4  az  v   n  f  d  h  d  n

In [15]:
cat_data.shape

(4209, 8)

In [27]:
cat_data.isnull().sum(axis =0).sort_values(ascending = False)

X8    0
X6    0
X5    0
X4    0
X3    0
X2    0
X1    0
X0    0
dtype: int64

In [52]:
cat_data.columns


Index(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype='object')

In [53]:
cat_data.X0.value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
am     18
i      18
aq     18
u      17
l      16
aw     16
ad     14
k      11
au     11
b      11
as     10
r      10
bc      6
ao      4
c       3
aa      2
q       2
ab      1
ac      1
g       1
Name: X0, dtype: int64

In [54]:
cat_data.X0.value_counts().sort_values(ascending =False)

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
am     18
i      18
aq     18
u      17
l      16
aw     16
ad     14
au     11
b      11
k      11
as     10
r      10
bc      6
ao      4
c       3
aa      2
q       2
ab      1
ac      1
g       1
Name: X0, dtype: int64

In [55]:
cat_data.X0.value_counts().sort_values(ascending = False).shape


(47,)

In [56]:
 for i in cat_data.columns:
   print(i ,':',len(cat_data[i].unique()),'labels')



X0 : 47 labels
X1 : 27 labels
X2 : 44 labels
X3 : 7 labels
X4 : 4 labels
X5 : 29 labels
X6 : 12 labels
X8 : 25 labels


In [57]:
pd.get_dummies(cat_data,drop_first= False , ).shape

(4209, 195)

In [58]:
pd.get_dummies(cat_data,drop_first= True).shape

(4209, 187)

In [59]:
cat_data.shape

(4209, 8)

In [61]:
cat_data.X1.value_counts()

aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
w      52
z      46
u      37
e      33
m      32
t      31
h      29
f      23
y      23
j      22
n      19
k      17
p       9
g       6
ab      3
d       3
q       3
Name: X1, dtype: int64

In [63]:
cat_data.X1.value_counts().shape

(27,)

In [64]:
cat_data.X2.value_counts().shape

(44,)

In [65]:
cat_data.X3.value_counts().shape

(7,)

In [66]:
cat_data.X4.value_counts().shape

(4,)

In [67]:
cat_data.X5.value_counts().shape

(29,)

In [68]:
cat_data.X6.value_counts().shape

(12,)

In [70]:
cat_data.X8.value_counts().shape

(25,)

In [71]:
top10_X0 = [i for i in cat_data.X1.value_counts().head(10).index]

In [72]:
top10_X0 

['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

In [73]:
cat_data.X1.value_counts().head(10)

aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
Name: X1, dtype: int64

In [82]:
sum10 = cat_data.X1.value_counts().head(10).sum()

In [83]:
sum10

3821

In [81]:
cat_data.shape

(4209, 8)

In [88]:
sum10/cat_data.shape

array([  0.90781658, 477.625     ])

In [87]:
p

array([  0.90781658, 477.625     ])

In [89]:
sum12 = cat_data.X1.value_counts().head(12).sum()

In [90]:
sum12

3919

In [91]:
sum12/cat_data.shape

array([  0.93110002, 489.875     ])