In [124]:
import numpy as np


In [125]:
import pandas as pd

In [218]:
df1 = pd.read_csv('C:/python/Covid_Latest/raw_data1.csv')
df2 = pd.read_csv('C:/python/Covid_Latest/raw_data2.csv')
df3 = pd.read_csv('C:/python/Covid_Latest/raw_data3.csv')
df4 = pd.read_csv('C:/python/Covid_Latest/raw_data4.csv')
df5 = pd.read_csv('C:/python/Covid_Latest/raw_data5.csv')
df6 = pd.read_csv('C:/python/Covid_Latest/raw_data6.csv')
df7 = pd.read_csv('C:/python/Covid_Latest/raw_data7.csv')
df8 = pd.read_csv('C:/python/Covid_Latest/raw_data8.csv')
df9 = pd.read_csv('C:/python/Covid_Latest/raw_data9.csv')
df10 = pd.read_csv('C:/python/Covid_Latest/raw_data10.csv')

In [153]:
df1.columns

Index(['Patient Number', 'State Patient Number', 'Date Announced',
       'Estimated Onset Date', 'Age Bracket', 'Gender', 'Detected City',
       'Detected District', 'Detected State', 'State code', 'Current Status',
       'Notes', 'Contracted from which Patient (Suspected)', 'Nationality',
       'Type of transmission', 'Status Change Date', 'Source_1', 'Source_2',
       'Source_3', 'Backup Notes', 'Num Cases'],
      dtype='object')

In [154]:
len(df1.columns)

21

In [155]:
len(df2.columns)

21

In [156]:
len(df3.columns)

20

In [157]:
df3.columns

Index(['Entry_ID', 'State Patient Number', 'Date Announced', 'Age Bracket',
       'Gender', 'Detected City', 'Detected District', 'Detected State',
       'State code', 'Num Cases', 'Current Status',
       'Contracted from which Patient (Suspected)', 'Notes', 'Source_1',
       'Source_2', 'Source_3', 'Nationality', 'Type of transmission',
       'Status Change Date', 'Patient Number'],
      dtype='object')

In [158]:
len(df4.columns)

20

In [159]:
df1.columns == df2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [160]:
df2.columns == df3.columns

ValueError: Lengths must match to compare

In [161]:
df3.columns == df4.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [162]:
len(df5.columns)

20

In [163]:
len(df6.columns)

20

In [164]:
len(df7.columns)

20

In [165]:
len(df8.columns)

20

In [166]:
len(df9.columns)

20

In [167]:
len(df10.columns)

20

In [168]:
df4.columns == df5.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [169]:
df5.columns==df6.columns 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [170]:
df6.columns == df7.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [171]:
df7.columns==df8.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [172]:
df8.columns == df9.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [173]:
 df9.columns==df10.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [174]:
#columns present in every table :
abc = list(set.intersection(*map(set,[df1,df2,df3,df4,df5,df6,df7,df8,df9,df10])))

In [175]:
abc

['Source_1',
 'Notes',
 'Age Bracket',
 'Contracted from which Patient (Suspected)',
 'State code',
 'Detected District',
 'Date Announced',
 'Detected State',
 'Patient Number',
 'Status Change Date',
 'Num Cases',
 'Nationality',
 'Type of transmission',
 'Detected City',
 'Gender',
 'Source_3',
 'Current Status',
 'State Patient Number',
 'Source_2']

In [176]:
len(abc)

19

In [177]:
p = set(df2).intersection(df3)
p

{'Age Bracket',
 'Contracted from which Patient (Suspected)',
 'Current Status',
 'Date Announced',
 'Detected City',
 'Detected District',
 'Detected State',
 'Gender',
 'Nationality',
 'Notes',
 'Num Cases',
 'Patient Number',
 'Source_1',
 'Source_2',
 'Source_3',
 'State Patient Number',
 'State code',
 'Status Change Date',
 'Type of transmission'}

In [178]:
len(p)

19

In [223]:
q =set(df4).difference(df2)

In [224]:
q
#featues more in d2 and not there in d3

{'Entry_ID'}

In [225]:
q2 =set(df2).difference(df3)

In [226]:
q2

{'Backup Notes', 'Estimated Onset Date'}

In [181]:
df2.columns

Index(['Patient Number', 'State Patient Number', 'Date Announced',
       'Estimated Onset Date', 'Age Bracket', 'Gender', 'Detected City',
       'Detected District', 'Detected State', 'State code', 'Current Status',
       'Notes', 'Contracted from which Patient (Suspected)', 'Nationality',
       'Type of transmission', 'Status Change Date', 'Source_1', 'Source_2',
       'Source_3', 'Backup Notes', 'Num Cases'],
      dtype='object')

In [182]:
df3.columns

Index(['Entry_ID', 'State Patient Number', 'Date Announced', 'Age Bracket',
       'Gender', 'Detected City', 'Detected District', 'Detected State',
       'State code', 'Num Cases', 'Current Status',
       'Contracted from which Patient (Suspected)', 'Notes', 'Source_1',
       'Source_2', 'Source_3', 'Nationality', 'Type of transmission',
       'Status Change Date', 'Patient Number'],
      dtype='object')

In [227]:
df3

Entry_ID State Patient Number Date Announced  Age Bracket Gender  \
0             1                  NaN     27/04/2020          NaN    NaN   
1             2                  NaN     27/04/2020          NaN    NaN   
2             3                  NaN     27/04/2020          NaN    NaN   
3             4                  NaN     27/04/2020         28.0      M   
4             5                  NaN     27/04/2020          NaN    NaN   
...         ...                  ...            ...          ...    ...   
10015     43270                  NaN     27/04/2020          NaN    NaN   
10016     43271                  NaN     27/04/2020          NaN    NaN   
10017     43272                  NaN     14/03/2020          NaN    NaN   
10018     43273                  NaN     14/03/2020          NaN    NaN   
10019     43274                  NaN     14/03/2020          NaN    NaN   

      Detected City Detected District    Detected State State code  Num Cases  \
0               NaN               NaN       West Bengal         WB       38.0   
1               NaN          Bhilwara         Rajasthan         RJ        2.0   
2               NaN            Jaipur         Rajasthan         RJ        9.0   
3          Surajpol            Jaipur         Rajasthan         RJ        1.0   
4               NaN         Jaisalmer         Rajasthan         RJ        1.0   
...             ...               ...               ...        ...        ...   
10015           NaN      Thoothukkudi        Tamil Nadu         TN       -1.0   
10016           NaN               NaN        Tamil Nadu         TN        1.0   
10017           NaN               NaN  Himachal Pradesh         HP        1.0   
10018           NaN               NaN  Himachal Pradesh         HP        1.0   
10019           NaN               NaN  Himachal Pradesh         HP        1.0   

       Current Status Contracted from which Patient (Suspected)  \
0        Hospitalized                                       NaN   
1        Hospitalized                                       NaN   
2        Hospitalized                                       NaN   
3            Deceased                                       NaN   
4        Hospitalized                                       NaN   
...               ...                                       ...   
10015        Deceased                                       NaN   
10016        Deceased                                       NaN   
10017  Migrated_Other                                       NaN   
10018  Migrated_Other                                       NaN   
10019  Migrated_Other                                       NaN   

                                 Notes  \
0                      Details awaited   
1                      Details awaited   
2                      Details awaited   
3                      Details awaited   
4                      Details awaited   
...                                ...   
10015                              NaN   
10016                              NaN   
10017  Entry for reduction from Active   
10018  Entry for reduction from Active   
10019  Entry for reduction from Active   

                                                Source_1 Source_2 Source_3  \
0                                           mohfw.gov.in      NaN      NaN   
1      https://twitter.com/ANI/status/125461859651442...      NaN      NaN   
2      https://twitter.com/ANI/status/125461859651442...      NaN      NaN   
3      https://twitter.com/ANI/status/125461859651442...      NaN      NaN   
4      https://twitter.com/ANI/status/125461859651442...      NaN      NaN   
...                                                  ...      ...      ...   
10015                                                NaN      NaN      NaN   
10016                                                NaN      NaN      NaN   
10017                                                NaN      NaN      NaN   
10018                                      

In [183]:
q2 =set(df2) - set(df3)
#second way of getting the differnce 

In [184]:
q2


{'Backup Notes', 'Estimated Onset Date'}

In [185]:
q3 =set(df3) - set(df2)

In [186]:
q3
#feature there in df3 but not in df2

{'Entry_ID'}

In [187]:
s= set(df2)

In [188]:
s

{'Age Bracket',
 'Backup Notes',
 'Contracted from which Patient (Suspected)',
 'Current Status',
 'Date Announced',
 'Detected City',
 'Detected District',
 'Detected State',
 'Estimated Onset Date',
 'Gender',
 'Nationality',
 'Notes',
 'Num Cases',
 'Patient Number',
 'Source_1',
 'Source_2',
 'Source_3',
 'State Patient Number',
 'State code',
 'Status Change Date',
 'Type of transmission'}

In [189]:
s2= set(df3)

In [190]:
s2

{'Age Bracket',
 'Contracted from which Patient (Suspected)',
 'Current Status',
 'Date Announced',
 'Detected City',
 'Detected District',
 'Detected State',
 'Entry_ID',
 'Gender',
 'Nationality',
 'Notes',
 'Num Cases',
 'Patient Number',
 'Source_1',
 'Source_2',
 'Source_3',
 'State Patient Number',
 'State code',
 'Status Change Date',
 'Type of transmission'}

In [192]:
df1 = df1.rename(columns ={"Patient Number":"Entry_ID"})

In [193]:
df1

Entry_ID State Patient Number Date Announced  Estimated Onset Date  \
0           1.0             KL-TS-P1     30/01/2020                   NaN   
1           2.0             KL-AL-P1     02/02/2020                   NaN   
2           3.0             KL-KS-P1     03/02/2020                   NaN   
3           4.0                DL-P1     02/03/2020                   NaN   
4           5.0                TS-P1     02/03/2020                   NaN   
...         ...                  ...            ...                   ...   
17359       NaN                  NaN     16/04/2020                   NaN   
17360       NaN                  NaN     18/04/2020                   NaN   
17361       NaN                  NaN     18/04/2020                   NaN   
17362       NaN                  NaN     19/04/2020                   NaN   
17363       NaN                  NaN     19/04/2020                   NaN   

      Age Bracket Gender             Detected City Detected District  \
0              20      F                  Thrissur          Thrissur   
1             NaN    NaN                 Alappuzha         Alappuzha   
2             NaN    NaN                 Kasaragod         Kasaragod   
3              45      M  East Delhi (Mayur Vihar)        East Delhi   
4              24      M                 Hyderabad         Hyderabad   
...           ...    ...                       ...               ...   
17359         NaN    NaN                       NaN               NaN   
17360         NaN    NaN                       NaN            Nagpur   
17361         NaN    NaN                       NaN               NaN   
17362         NaN    NaN                       NaN            Nagpur   
17363         NaN    NaN                       NaN               NaN   

      Detected State State code  ...  \
0             Kerala         KL  ...   
1             Kerala         KL  ...   
2             Kerala         KL  ...   
3              Delhi         DL  ...   
4          Telangana         TG  ...   
...              ...        ...  ...   
17359    Maharashtra         MH  ...   
17360    Maharashtra         MH  ...   
17361    Maharashtra         MH  ...   
17362    Maharashtra         MH  ...   
17363    Maharashtra         MH  ...   

                                                   Notes  \
0                                   Travelled from Wuhan   
1                                   Travelled from Wuhan   
2                                   Travelled from Wuhan   
3                          Travelled from Austria, Italy   
4      Travelled from Dubai to Bangalore on 20th Feb,...   
...                                                  ...   
17359                      Correction for district count   
17360                      Correction for district count   
17361                      Correction for district count   
17362                      Correction for district count   
17363                      Correction for district count   

      Contracted from which Patient (Suspected) Nationality  \
0                                           NaN       India   
1                                           NaN       India   
2                                           NaN       India   
3                                           NaN       India   
4                                           NaN       India   
...                                         ...         ...   
17359                                       NaN         NaN   
17360                                       NaN         NaN   
17361                                       NaN         NaN   
17362                                       NaN         NaN   
17363                                       NaN         NaN   

      Type of transmission Status Change Date  \
0                 Imported         14/02/2020   
1                 Imported         14/02/2020   
2                 Imported         14/02/2020   
3                 Imported         15/03/2020   
4            

In [194]:
df2 = df2.rename(columns ={"Patient Number":"Entry_ID"})

In [195]:
df2

Entry_ID State Patient Number Date Announced  Estimated Onset Date  \
0       17307.0                  NaN     20/04/2020                   NaN   
1       17308.0                  NaN     20/04/2020                   NaN   
2       17309.0                  NaN     20/04/2020                   NaN   
3       17310.0                  NaN     20/04/2020                   NaN   
4       17311.0                  NaN     20/04/2020                   NaN   
...         ...                  ...            ...                   ...   
10814       NaN                  NaN     22/04/2020                   NaN   
10815       NaN                  NaN     24/04/2020                   NaN   
10816       NaN                  NaN     24/04/2020                   NaN   
10817       NaN                  NaN     25/04/2020                   NaN   
10818       NaN                  NaN     25/04/2020                   NaN   

       Age Bracket Gender Detected City Detected District Detected State  \
0             48.0      M           NaN           Bhadrak         Odisha   
1             55.0      M           NaN           Bhadrak         Odisha   
2             57.0      M           NaN           Bhadrak         Odisha   
3             58.0      M           NaN           Bhadrak         Odisha   
4             66.0      M           NaN           Bhadrak         Odisha   
...            ...    ...           ...               ...            ...   
10814          NaN    NaN           NaN               NaN    Maharashtra   
10815          NaN    NaN           NaN            Nagpur    Maharashtra   
10816          NaN    NaN           NaN               NaN    Maharashtra   
10817          NaN    NaN           NaN            Nagpur    Maharashtra   
10818          NaN    NaN           NaN               NaN    Maharashtra   

      State code  ...                          Notes  \
0             OR  ...                Details awaited   
1             OR  ...                Details awaited   
2             OR  ...                Details awaited   
3             OR  ...                Details awaited   
4             OR  ...                Details awaited   
...          ...  ...                            ...   
10814         MH  ...  Correction for district count   
10815         MH  ...  Correction for district count   
10816         MH  ...  Correction for district count   
10817         MH  ...  Correction for district count   
10818         MH  ...  Correction for district count   

      Contracted from which Patient (Suspected) Nationality  \
0                                           NaN         NaN   
1                                           NaN         NaN   
2                                           NaN         NaN   
3                                           NaN         NaN   
4                                           NaN         NaN   
...                                         ...         ...   
10814                                       NaN         NaN   
10815                                       NaN         NaN   
10816                                       NaN         NaN   
10817                                       NaN         NaN   
10818                                       NaN         NaN   

       Type of transmission Status Change Date  \
0                       NaN         20/04/2020   
1                       NaN         20/04/2020   
2                       NaN         20/04/2020   
3                       NaN         20/04/2020   
4                       NaN         20/04/2020   
...                     ...                ...   
10814                   NaN                NaN   
10815                   NaN                NaN   
10816                   NaN                NaN   
10817                   NaN                NaN   
10818                   NaN                NaN   

                                                Source_1 Source_2 Source_3  \
0      https://twitter.com/the_hindu/status/125205985...    

In [196]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10020 entries, 0 to 10019
Data columns (total 20 columns):
Entry_ID                                     10020 non-null int64
State Patient Number                         5138 non-null object
Date Announced                               10020 non-null object
Age Bracket                                  5183 non-null float64
Gender                                       4654 non-null object
Detected City                                421 non-null object
Detected District                            9934 non-null object
Detected State                               10015 non-null object
State code                                   10015 non-null object
Num Cases                                    10019 non-null float64
Current Status                               10020 non-null object
Contracted from which Patient (Suspected)    241 non-null object
Notes                                        1931 non-null object
Source_1                    

In [197]:
df2 = df2.drop(['Backup Notes', 'Estimated Onset Date'],axis=1)

In [198]:
df1 = df1.drop(['Backup Notes', 'Estimated Onset Date'],axis=1)

In [202]:
len(df1.columns)

19

In [206]:
df1.columns

Index(['Entry_ID', 'State Patient Number', 'Date Announced', 'Age Bracket',
       'Gender', 'Detected City', 'Detected District', 'Detected State',
       'State code', 'Current Status', 'Notes',
       'Contracted from which Patient (Suspected)', 'Nationality',
       'Type of transmission', 'Status Change Date', 'Source_1', 'Source_2',
       'Source_3', 'Num Cases'],
      dtype='object')

In [207]:
len(df1.columns)

19

In [114]:
df1

Entry_ID State Patient Number Date Announced Age Bracket Gender  \
0           1.0             KL-TS-P1     30/01/2020          20      F   
1           2.0             KL-AL-P1     02/02/2020         NaN    NaN   
2           3.0             KL-KS-P1     03/02/2020         NaN    NaN   
3           4.0                DL-P1     02/03/2020          45      M   
4           5.0                TS-P1     02/03/2020          24      M   
...         ...                  ...            ...         ...    ...   
17359       NaN                  NaN     16/04/2020         NaN    NaN   
17360       NaN                  NaN     18/04/2020         NaN    NaN   
17361       NaN                  NaN     18/04/2020         NaN    NaN   
17362       NaN                  NaN     19/04/2020         NaN    NaN   
17363       NaN                  NaN     19/04/2020         NaN    NaN   

                  Detected City Detected District Detected State State code  \
0                      Thrissur          Thrissur         Kerala         KL   
1                     Alappuzha         Alappuzha         Kerala         KL   
2                     Kasaragod         Kasaragod         Kerala         KL   
3      East Delhi (Mayur Vihar)        East Delhi          Delhi         DL   
4                     Hyderabad         Hyderabad      Telangana         TG   
...                         ...               ...            ...        ...   
17359                       NaN               NaN    Maharashtra         MH   
17360                       NaN            Nagpur    Maharashtra         MH   
17361                       NaN               NaN    Maharashtra         MH   
17362                       NaN            Nagpur    Maharashtra         MH   
17363                       NaN               NaN    Maharashtra         MH   

      Current Status                                              Notes  \
0          Recovered                               Travelled from Wuhan   
1          Recovered                               Travelled from Wuhan   
2          Recovered                               Travelled from Wuhan   
3          Recovered                      Travelled from Austria, Italy   
4          Recovered  Travelled from Dubai to Bangalore on 20th Feb,...   
...              ...                                                ...   
17359   Hospitalized                      Correction for district count   
17360   Hospitalized                      Correction for district count   
17361   Hospitalized                      Correction for district count   
17362   Hospitalized                      Correction for district count   
17363   Hospitalized                      Correction for district count   

      Contracted from which Patient (Suspected) Nationality  \
0                                           NaN       India   
1                                           NaN       India   
2                                           NaN       India   
3                                           NaN       India   
4                                           NaN       India   
...                                         ...         ...   
17359                                       NaN         NaN   
17360                                       NaN         NaN   
17361                                       NaN         NaN   
17362                                       NaN         NaN   
17363                                       NaN         NaN   

      Type of transmission Status Change Date  \
0                 Imported         14/02/2020   
1                 Imported         14/02/2020   
2                 Imported         14/02/2020   
3                 Imported         15/03/2020   
4                 Imported         02/03/2020   
...                    ...                ...   
17359                  NaN                NaN   
17360                  NaN                NaN   
17361                  NaN                NaN   
17362                

In [228]:
df2

Patient Number State Patient Number Date Announced  \
0             17307.0                  NaN     20/04/2020   
1             17308.0                  NaN     20/04/2020   
2             17309.0                  NaN     20/04/2020   
3             17310.0                  NaN     20/04/2020   
4             17311.0                  NaN     20/04/2020   
...               ...                  ...            ...   
10814             NaN                  NaN     22/04/2020   
10815             NaN                  NaN     24/04/2020   
10816             NaN                  NaN     24/04/2020   
10817             NaN                  NaN     25/04/2020   
10818             NaN                  NaN     25/04/2020   

       Estimated Onset Date  Age Bracket Gender Detected City  \
0                       NaN         48.0      M           NaN   
1                       NaN         55.0      M           NaN   
2                       NaN         57.0      M           NaN   
3                       NaN         58.0      M           NaN   
4                       NaN         66.0      M           NaN   
...                     ...          ...    ...           ...   
10814                   NaN          NaN    NaN           NaN   
10815                   NaN          NaN    NaN           NaN   
10816                   NaN          NaN    NaN           NaN   
10817                   NaN          NaN    NaN           NaN   
10818                   NaN          NaN    NaN           NaN   

      Detected District Detected State State code  ...  \
0               Bhadrak         Odisha         OR  ...   
1               Bhadrak         Odisha         OR  ...   
2               Bhadrak         Odisha         OR  ...   
3               Bhadrak         Odisha         OR  ...   
4               Bhadrak         Odisha         OR  ...   
...                 ...            ...        ...  ...   
10814               NaN    Maharashtra         MH  ...   
10815            Nagpur    Maharashtra         MH  ...   
10816               NaN    Maharashtra         MH  ...   
10817            Nagpur    Maharashtra         MH  ...   
10818               NaN    Maharashtra         MH  ...   

                               Notes  \
0                    Details awaited   
1                    Details awaited   
2                    Details awaited   
3                    Details awaited   
4                    Details awaited   
...                              ...   
10814  Correction for district count   
10815  Correction for district count   
10816  Correction for district count   
10817  Correction for district count   
10818  Correction for district count   

      Contracted from which Patient (Suspected) Nationality  \
0                                           NaN         NaN   
1                                           NaN         NaN   
2                                           NaN         NaN   
3                                           NaN         NaN   
4                                           NaN         NaN   
...                                         ...         ...   
10814                                       NaN         NaN   
10815                                       NaN         NaN   
10816                                       NaN         NaN   
10817                                       NaN         NaN   
10818                                       NaN         NaN   

       Type of transmission Status Change Date  \
0                       NaN         20/04/2020   
1                       NaN         20/04/2020   
2                       NaN         20/04/2020   
3                       NaN         20/04/2020   
4                       NaN         20/04/2020   
...                     ...                ...   
10814                   NaN                NaN   
10815                   NaN                NaN   
10816                   NaN                NaN   
10817                   NaN                NaN   
10818   